### ISSUE TITLE
Enhancement: Feature caching

### ISSUE THREAD

**Issue by robocoder** [vipsoft/JiraExtension#1]
We can use the 'updated' property of each issue as a timestamp, and thus, query only for new/modified issues in subsequent runs

Caveat:  won't detect old issues that have been deleted or no longer meet the jql criteria.

**Comment by everzet** [comment]
Do you have ability to delete issues in Jira? In GitHub for example, you could only close them. Close is evaluated as status change and issue is still in the system.

**Comment by robocoder** [comment]
Yes, in Jira, the owner (presumably anyone with appropriate privileges) can delete issues.

Also, in Jira, an issue that is moved between projects will change its key, e.g., PROJECTA-101 may become PROJECTB-25.

**Comment by robocoder** [comment]
Implemented in v1.0.1
