### ISSUE TITLE
Run a set of JIRA issues

### ISSUE THREAD

**Issue by gkini** [vipsoft/JiraExtension#10]
Hi,

I am a newbie to the Behat and the JIRA extension . Could you please let me know if there is a way to group JIRA tests together, similar to tags in Behat?

**Comment by gkini** [comment]
I am currently using "behat jira:issue_number"

**Comment by robocoder** [comment]
Currently not supported.  In the interim, try adding support for a comma separated list, eg jira:issue-1,issue-2,etc-n via the FeatureLoaderService.php.

**Comment by mandarille** [comment]
Any plans to add this feature? Would be nice to be able to run tests in jira based on tags or jql.

**Comment by robocoder** [comment]
Sure, but Iow on my list of priorities.

**Comment by gkini** [comment]
Thanks for the idea. Comma separated lists sounds like a good idea.
