### ISSUE TITLE
Issue Mapper

### ISSUE THREAD

**Issue by srizzling** [vipsoft/JiraExtension#13]
How hard would it be to implement a method of pushing features to specific jira issues via tags.

**Comment by robocoder** [comment]
Please elaborate.   I don't fully understand the question.

**Comment by srizzling** [comment]
https://github.com/Behat/GithubExtension Similar to this extension. It has the ability to push Behat Feature files to specfic issues. I would like to integrate it with Jira in a similar fashion. Instead of pull features from Jira Issues, I would like to push local feature files to Jira Issues.

**Comment by robocoder** [comment]
I see.  Technically, not extremely difficult.

Is this simply to import existing .feature files into Jira?  Or more frequently used where it might require two-way syncing?

**Comment by srizzling** [comment]
For my preferences I like the first one, but additionaly support for two-way syncing would be cool too :)

**Comment by srizzling** [comment]
Would you be able to point me in right direction on how I would set things up.

**Comment by srizzling** [comment]
any more on this?
