### ISSUE TITLE
Suggested Name Change?

### ISSUE THREAD

**Issue by srizzling** [vipsoft/JiraExtension#15]
Currently working on implementing this feature: https://github.com/vipsoft/JiraExtension/issues/13

I have completed a working prototype, will need to refactor and write up some unit tests before I can push it back to open source. 

Currently there is a AfterScenarioListener.php file. I was hoping to suggest a name change, to JiraServiceListener.php which will allow for other hooks such as AfterSuite. This is because I do not want to push per scenario basis but after the whole suite is finished for performance reasons. 

And before I made a change to architecture of the plugin I was going to ask if it were a good idea.

**Comment by robocoder** [comment]
Sure, let's rename.  IIRC I used HookListener in another extension, so for consistency, that would be my preference.

**Comment by srizzling** [comment]
Sounds Good! I will make a separate pull request for the name change.
