### ISSUE TITLE
[question] Comments outside code tags

### ISSUE THREAD

**Issue by naxhh** [vipsoft/JiraExtension#21]
Hi!

I'm using the jira code tags to enclose features and scenarios as the wiki-page shows (http://extensions.behat.org/jira-extension/).

But I noticed you can't add text outside (after or before) because the parser breaks.
It would be great that the system allows adding some text.

```
[Behat\Gherkin\Exception\ParserException]                                                                        
  Expected Comment or Scenario or Outline or Step token, but got Text on line: 19 in file: https://jira/issue#

```

We use a lot the description of the task to add more information or explanations about things related to the task, or references to wikis, other issues etc.

There is any reason we can't parse only the content inside code tags and ignore the rest?

Regards.

**Comment by robocoder** [comment]
Feel free to submit a PR.  The current implementation is a simple regex.

https://github.com/vipsoft/JiraExtension/blob/master/src/VIPSoft/JiraExtension/Service/FeatureLoaderService.php#L119
