### ISSUE TITLE
SOAP UI problems

### ISSUE THREAD

**Issue by srizzling** [vipsoft/JiraExtension#22]
We been having a few problems with the current verison of the 2.5 branch.

This is error we are having 

SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://mycompany.jira.com/rpc/soap/jirasoapservice-v2?wsdl' : failed to load external entity "http://mycompany.jira.com/rpc/soap/jirasoapservice-v2?wsdl"

The link actual returns a valid WSDL. The extension also worked before, with our own branch that we were maintaining with all the improvements made in a previous PR. 

I have reason to believe this is because of the recent upgrades to add proxy configuration. Wasn't exactly sure what the actual cause is. /cc @jeffreyguo

Intial thoughts is that it is trying to inject null params into the proxy config which causes an error within SoapClient

**Comment by srizzling** [comment]
Would I use something like on-invalid="ignored"for the params  or does that not do what I think it does?

**Comment by robocoder** [comment]
Sorry.  Proxy support was a short term solution -- I unfortunately did the bare minimum fix/test to the original PR.

I'm going to change it to a compiler pass, and open up the soapclient options.

**Comment by srizzling** [comment]
Thats cool no worries!

**Comment by srizzling** [comment]
Closing this, as its like 4 years old.. I don't use the project anymore :P
