### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by jakzal** [vipsoft/JiraExtension#4]
Currently the extension is not covered by unit tests. I could work on it but first I need to know you'll accept my PR ;)

I have one small suggestion. JiraService is not easy to unit test since it creates SoapClient directly inside the connect() method. We should rather pass an instance of SoapClient in JiraService's constructor or make that JiraService extends the SoapClient.

I also suggest that instead of hard coding the "/rpc/soap/jirasoapservice-v2?wsdl" part in the JiraService we make it configurable (as part of host, might be good to change the name of the config variable, i.e. wsdl_url).

**Comment by robocoder** [comment]
Please do.  I've stubbed somethings as part of a general code cleanup.

**Comment by jakzal** [comment]
Do you think passing a class name is the way to go? I'd just pass an instance of SoapClient to JiraService (it's still not possible to mock it in an unit test). 

Anyway, I'll prepare PR and you'll see if you like it.

**Comment by robocoder** [comment]
At this point, I'm not 100% sure about passing the class name ... it's all in flux until I implement issue #3.

**Comment by jakzal** [comment]
Ok, in such case I'll send a PR now. I didn't write all the tests yet but it'd be great if I got some feedback.

**Comment by robocoder** [comment]
Thanks for the PR.
